apiVersion: v1

services:
  - name: frontend-nextjs
    type: server
    repo: ryvn-mango/nextjs
    build:
      # buildpack: nixpack
      dockerfile: Dockerfile
  - name: minute-cron-job
    type: job
    repo: ryvn-mango/minute-cron-job
    build:
      buildpack: nixpack
  - name: asset-manager
    type: helm-chart
    repo: ryvn-mango/charts
    build:
      chartPath: asset-manager
  

environments:
  - name: sap
    setup: customer-controlled
    provider:
      type: aws
    customerEmail: customer@ryvncloud.com
    installations:
      - service: asset-manager
