kind: PromotionPipeline
metadata:
  name: product-team-pipeline
spec:
  paths:
    - sourceChannel: branch:main
      targetChannel: production
    - sourceChannel: production
      targetChannel: stable
